/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.phodu.govt.util.foodsecurity;

import java.io.IOException;
import java.util.List;

public class App {
	public static void main(String[] args) throws IOException {
		if (args.length == 0) {
			System.out.print("Please pass input file name");
		}
		String inputFileName = args[0];
		String outputFileName = (args.length > 1) ? args[1] : "parsed.xlsx";
		String tempFileName = inputFileName + ".temp";

		Pdf2HtmlConverter converter = new Pdf2HtmlConverter(inputFileName, tempFileName);
		converter.convert();

		FoodSecurityCardHtmlParser htmlParser = new FoodSecurityCardHtmlParser(tempFileName);
		List<FoodSecurityCard> foodSecurityCards = htmlParser.parse();

		FoodSecurityCardExcelWriter excelWriter = new FoodSecurityCardExcelWriter(outputFileName);
		for (FoodSecurityCard foodSecurityCard : foodSecurityCards)
			excelWriter.write(foodSecurityCard);
		excelWriter.close();
	}
}
